[default]
check-filename = true
language = ["pt", "en"]

[files]
extend-exclude = [
  "CHANGELOG.md",
  "SECURITY.md",
  "CODE_OF_CONDUCT.md",
  "astro.config.ts",
  "package-lock.json",
  "package.json",
  "CONTRIBUTING.md",
  "biome.json",
  "FRONTEND.md",
  "build",
  "LICENSE",
  "commitlint.config.js",
  "tsconfig.json",
  "README.md",
  "node_modules",
  "typos.toml",
  "public"
]

[default.extend-words]
stretch = "stretch"
container = "container"
collapsible = "collapsible"
style = "style"